import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    headerGradient:{
        height:160
    },
    linearGradient:{
        height:106,
        borderRadius:10
    },
    square:{
        flexDirection:'row',
        flex:1,justifyContent:'center'
    },
    texthead:{
        marginTop:16,
        marginLeft:8,
        marginBottom:16,
        fontSize:17,
        fontWeight:'bold'
    },
    measurements:{
        fontSize:17,
        color:'white',
        textAlign:'center',
        marginTop:'auto',
        marginBottom:'auto'
    },
    inforitem:{
        textAlign:'center',
        fontSize:17,
        marginTop:16,
        fontWeight:'bold'
    },
    regime:{
        flex:1,
        flexDirection:'row'
    },
    inforRegime:{
        flex:1,
        flexDirection:'row',
        justifyContent:'flex-end',
        marginRight:16,
        marginTop:16
    },
    type:{
        fontSize:17,
        marginRight:16
    },
    kcal:{
        fontSize:17
    },
    cover:{
        flex:1,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    name:{
     fontSize:24,
     color:'white',
     fontWeight:'bold'
    },
    email:{
     fontSize:14,
     color:'white'
    },
    infogroup:{
        marginLeft: 16
    },
    logout:{
        width:99,
        height:29,
        backgroundColor:'#9E9CFF',
        borderRadius:30,
        marginLeft:16,
        marginTop:8
    },
    textlogout:{
        textAlign:'center',
        color:'white',
        marginTop:'auto',
        marginBottom:'auto',
        fontWeight:'600'
    },
    watchmore:{
        flex:1,
        flexDirection:'row',
        justifyContent:'flex-end',
        marginRight:16,
        marginTop:16
    }
})
